name: Build and Publish Garry's Mod Addons

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        choco install zip -y

    - name: Download gmpublisher
      run: |
        $url = "https://github.com/WilliamVenner/gmpublisher/releases/download/v2.11.0/gmpublisher_2.11.0_x64.zip"
        $dest = "$Env:USERPROFILE\gmpublisher.zip"
        Invoke-WebRequest -Uri $url -OutFile $dest
        Expand-Archive -Path $dest -DestinationPath "$Env:USERPROFILE\gmpublisher"
        Remove-Item $dest
        Write-Host "gmpublisher installed at $Env:USERPROFILE\gmpublisher"

    - name: Set Steam API Key
      run: |
        echo "STEAM_API_KEY=${{ secrets.STEAM_API_KEY }}" >> $Env:GITHUB_ENV

    - name: Pack and publish addons
      run: |
        $gmpub = "$Env:USERPROFILE\gmpublisher\gmpublisher.exe"
        mkdir build
        Get-ChildItem -Directory ./addons | ForEach-Object {
            $addonName = $_.Name
            Write-Host "Packing $addonName..."
            & $gmpub pack $_.FullName --output ".\build\$addonName.gma"
            Write-Host "Publishing $addonName to Steam Workshop..."
            & $gmpub publish ".\build\$addonName.gma" `
              --title $addonName `
              --description "Automatically published via GitHub Actions" `
              --tags "tag1,tag2" `
              --steam-key $Env:STEAM_API_KEY
        }

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gmod-addons
        path: ./build/*.gma
