name: Build All Garry's Mod Addons

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y wget unzip lib32gcc-s1 zip

    - name: Install SteamCMD
      run: |
        mkdir -p $HOME/steamcmd
        cd $HOME/steamcmd
        wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
        tar -xvzf steamcmd_linux.tar.gz
        $HOME/steamcmd/steamcmd.sh +quit

    - name: Install Garry's Mod tools
      run: |
        mkdir -p $HOME/gmod-tools
        $HOME/steamcmd/steamcmd.sh +login anonymous \
          +force_install_dir $HOME/gmod-tools \
          +app_update 4020 validate +quit
        GMOD_BIN="$HOME/gmod-tools/steamapps/common/GarrysModDS/bin"
        chmod +x "$GMOD_BIN/gmad"
        echo "GMod tools installed at $GMOD_BIN"

    - name: Pack all addons
      run: |
        mkdir -p ./build
        GMOD_BIN="$HOME/gmod-tools/steamapps/common/GarrysModDS/bin"
        for dir in ./addons/*/ ; do
          name=$(basename "$dir")
          echo "Packing $name ..."
          "$GMOD_BIN/gmad" create -folder "$dir" -out "./build/${name}.gma"
        done

    - name: Log packed addons
      run: |
        echo "Packed .gma files:"
        ls -1 ./build/*.gma

    - name: Upload individual .gma files
      uses: actions/upload-artifact@v4
      with:
        name: gmod-addons-individual
        path: ./build/*.gma

    - name: Archive all .gma into ZIP
      run: |
        zip -r ./build/addons.zip ./build/*.gma
        echo "Files in ZIP:"
        unzip -l ./build/addons.zip

    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v4
      with:
        name: gmod-addons-zip
        path: ./build/addons.zip
