name: Build All Garry's Mod Addons

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y wget unzip lib32gcc-s1

    - name: Install SteamCMD
      run: |
        mkdir -p $HOME/steamcmd
        cd $HOME/steamcmd
        wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
        tar -xvzf steamcmd_linux.tar.gz
        $HOME/steamcmd/steamcmd.sh +quit

    - name: Install Garry's Mod tools
      run: |
        mkdir -p $HOME/gmod-tools
        $HOME/steamcmd/steamcmd.sh +login anonymous \
          +force_install_dir $HOME/gmod-tools \
          +app_update 4020 validate +quit
        ls $HOME/gmod-tools/bin/

    - name: Pack all addons
      run: |
        mkdir -p ./build
        for dir in ./addons/*/ ; do
          name=$(basename "$dir")
          echo "Packing $name ..."
          $HOME/gmod-tools/bin/gmad create \
            -folder "$dir" \
            -out "./build/${name}.gma"
        done

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gmod-addons
        path: ./build/*.gma
