name: Build and Publish Garry's Mod Addons

on:
  push:
    branches: [ "main" ]
    paths:
      - 'addons/**'

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: choco install zip -y

    - name: Download and install gmpublisher
      run: |
        $url = "https://github.com/WilliamVenner/gmpublisher/releases/download/2.11.0/gmpublisher_2.11.0_x64_en-US.msi"
        $msiPath = "$Env:USERPROFILE\gmpublisher.msi"
        Invoke-WebRequest -Uri $url -OutFile $msiPath
        msiexec /i $msiPath /qn
        Remove-Item $msiPath
        Write-Host "gmpublisher installed."

    - name: Set Steam API Key
      run: echo "STEAM_API_KEY=${{ secrets.STEAM_API_KEY }}" >> $Env:GITHUB_ENV

    - name: Pack and publish addons
      run: |
        # Найти реальный путь gmpublisher.exe
        $gmpubPath = Join-Path "C:\Program Files\gmpublisher" "gmpublisher.exe"
        if (-not (Test-Path $gmpubPath)) {
            $gmpubPath = Join-Path "C:\Program Files (x86)\gmpublisher" "gmpublisher.exe"
        }
        if (-not (Test-Path $gmpubPath)) {
            Write-Error "gmpublisher.exe not found!"
            exit 1
        }
        Write-Host "Using gmpublisher at $gmpubPath"

        mkdir build
        Get-ChildItem -Directory ./addons | ForEach-Object {
            $addonName = $_.Name
            Write-Host "Packing $addonName..."
            & "$gmpubPath" pack $_.FullName --output ".\build\$addonName.gma"
            Write-Host "Publishing $addonName to Steam Workshop..."
            & "$gmpubPath" publish ".\build\$addonName.gma" `
              --title $addonName `
              --description "Automatically published via GitHub Actions" `
              --tags "tag1,tag2" `
              --steam-key $Env:STEAM_API_KEY
        }

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gmod-addons
        path: ./build/*.gma