name: Build All Garry's Mod Addons

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip zip

    - name: Download gmad
      run: |
        mkdir -p $HOME/gmad
        cd $HOME/gmad
        wget -O gmad_linux.zip https://github.com/Facepunch/garrysmod-sdk/releases/download/v2025.07/gmad_linux.zip
        unzip gmad_linux.zip
        chmod +x gmad
        echo "gmad installed at $HOME/gmad/gmad"

    - name: Pack all addons
      run: |
        mkdir -p ./build
        GMAD_BIN="$HOME/gmad/gmad"
        for dir in ./addons/*/ ; do
          name=$(basename "$dir")
          echo "Packing $name ..."
          "$GMAD_BIN" create -folder "$dir" -out "./build/${name}.gma"
        done

    - name: Log packed addons
      run: |
        echo "Packed .gma files:"
        ls -1 ./build/*.gma

    - name: Upload individual .gma files
      uses: actions/upload-artifact@v4
      with:
        name: gmod-addons-individual
        path: ./build/*.gma

    - name: Archive all .gma into ZIP
      run: |
        zip -r ./build/addons.zip ./build/*.gma
        echo "Files in ZIP:"
        unzip -l ./build/addons.zip

    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v4
      with:
        name: gmod-addons-zip
        path: ./build/addons.zip
