name: Build and Publish Garry's Mod Addon

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip libwebkit2gtk-4.1-0 libjavascriptcoregtk-4.1-0 zip

    - name: Set Steam API Key
      run: echo "STEAM_API_KEY=${{ secrets.STEAM_API_KEY }}" >> $GITHUB_ENV

    - name: Download gmpublisher
      run: |
        mkdir -p $HOME/gmpublisher
        cd $HOME/gmpublisher
        wget -O gmpublisher_linux.tar.gz https://github.com/WilliamVenner/gmpublisher/releases/download/v2.11.0/gmpublisher_2.11.0_linux_x86_64.tar.gz
        tar -xzf gmpublisher_linux.tar.gz
        chmod +x gmpublisher

    - name: Pack and publish addons
      run: |
        mkdir -p ./build
        GMPUB="$HOME/gmpublisher/gmpublisher"
        for dir in ./addons/*/; do
          name=$(basename "$dir")
          echo "Packing $name..."
          "$GMPUB" pack "$dir" --output "./build/$name.gma"
          echo "Publishing $name to Steam Workshop..."
          "$GMPUB" publish "./build/$name.gma" \
            --title "$name" \
            --description "Automatically published via GitHub Actions" \
            --tags "tag1,tag2" \
            --steam-key "$STEAM_API_KEY"
        done

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gmod-addons
        path: ./build/*.gma
